/**
 * Mototrek E-Commerce Relational Demo Data Seeder
 * Populates real connected data into backend models:
 * Users, Products, Orders, Coupons, Payments, Shipments
 * Spanning dates across Today, Yesterday, This Week, This Month, Lifetime.
 */

const { hashPassword } = require('./utils/hash');
const UserModel = require('./models/user.model');
const ProductModel = require('./models/product.model');
const OrderModel = require('./models/order.model');
const CouponModel = require('./models/coupon.model');
const PaymentModel = require('./models/payment.model');
const ShippingModel = require('./models/shipping.model');
const PosBillModel = require('./models/posBill.model');
const SupplierModel = require('./models/supplier.model');
const PurchaseOrderModel = require('./models/purchaseOrder.model');
const AccountsModel = require('./models/accounts.model');

// Date Helper in IST (Asia/Kolkata)
const now = new Date();
const daysAgo = (d, hours = 10, mins = 30) => {
  const date = new Date(now.getTime() - d * 24 * 3600 * 1000);
  date.setHours(hours, mins, 0, 0);
  return date.toISOString();
};

const seedDemoData = () => {
  console.log('🌱 Starting Mototrek Relational Demo Data Seeder...');

  // 1. DEMO USERS (12 Customers)
  const demoUsers = [
    {
      id: 'usr-101',
      name: 'Rahul Sharma',
      email: 'rahul.s@gmail.com',
      mobile: '9823011234',
      passwordHash: hashPassword('Rider@2026'),
      createdAt: daysAgo(25),
      addresses: [
        {
          id: 'addr-1',
          name: 'Rahul Sharma',
          mobile: '9823011234',
          house: 'Flat 402, Royal Palms',
          street: 'Baner Road',
          landmark: 'Near Crossword',
          city: 'Pune',
          state: 'Maharashtra',
          pincode: '411045',
          type: 'Home',
          isDefault: true,
        },
      ],
    },
    {
      id: 'usr-102',
      name: 'Vikram Patel',
      email: 'vikram.patel@yahoo.com',
      mobile: '9890123456',
      passwordHash: hashPassword('Rider@2026'),
      createdAt: daysAgo(20),
      addresses: [
        {
          id: 'addr-2',
          name: 'Vikram Patel',
          mobile: '9890123456',
          house: '12B, Sea Crest Towers',
          street: 'Marine Drive',
          city: 'Mumbai',
          state: 'Maharashtra',
          pincode: '400020',
          type: 'Home',
          isDefault: true,
        },
      ],
    },
    {
      id: 'usr-103',
      name: 'Ananya Iyer',
      email: 'ananya.i@gmail.com',
      mobile: '9845098765',
      passwordHash: hashPassword('Rider@2026'),
      createdAt: daysAgo(12),
      addresses: [
        {
          id: 'addr-3',
          name: 'Ananya Iyer',
          mobile: '9845098765',
          house: '#45, 10th Main',
          street: 'Indiranagar',
          city: 'Bengaluru',
          state: 'Karnataka',
          pincode: '560038',
          type: 'Work',
          isDefault: true,
        },
      ],
    },
    {
      id: 'usr-104',
      name: 'Amit Verma',
      email: 'amit.v@hotmail.com',
      mobile: '9811223344',
      passwordHash: hashPassword('Rider@2026'),
      createdAt: daysAgo(10),
      addresses: [
        {
          id: 'addr-4',
          name: 'Amit Verma',
          mobile: '9811223344',
          house: 'C-14, Vasant Kunj',
          street: 'Nelson Mandela Marg',
          city: 'New Delhi',
          state: 'Delhi',
          pincode: '110070',
          type: 'Home',
          isDefault: true,
        },
      ],
    },
    {
      id: 'usr-105',
      name: 'Rohan Deshmukh',
      email: 'rohan.d@gmail.com',
      mobile: '9765432109',
      passwordHash: hashPassword('Rider@2026'),
      createdAt: daysAgo(8),
      addresses: [
        {
          id: 'addr-5',
          name: 'Rohan Deshmukh',
          mobile: '9765432109',
          house: 'B-201, Green Acres',
          street: 'Kothrud',
          city: 'Pune',
          state: 'Maharashtra',
          pincode: '411038',
          type: 'Home',
          isDefault: true,
        },
      ],
    },
    {
      id: 'usr-106',
      name: 'Sneha Kulkarni',
      email: 'sneha.k@gmail.com',
      mobile: '9922334455',
      passwordHash: hashPassword('Rider@2026'),
      createdAt: daysAgo(4),
      addresses: [
        {
          id: 'addr-6',
          name: 'Sneha Kulkarni',
          mobile: '9922334455',
          house: 'Plot 78, College Road',
          street: 'Gangapur Road',
          city: 'Nashik',
          state: 'Maharashtra',
          pincode: '422005',
          type: 'Home',
          isDefault: true,
        },
      ],
    },
    {
      id: 'usr-107',
      name: 'Kabir Malhotra',
      email: 'kabir.m@outlook.com',
      mobile: '9876543210',
      passwordHash: hashPassword('Rider@2026'),
      createdAt: daysAgo(3),
      addresses: [
        {
          id: 'addr-7',
          name: 'Kabir Malhotra',
          mobile: '9876543210',
          house: 'House 512, Sector 17',
          street: 'Madhya Marg',
          city: 'Chandigarh',
          state: 'Punjab',
          pincode: '160017',
          type: 'Home',
          isDefault: true,
        },
      ],
    },
    {
      id: 'usr-108',
      name: 'Priya Nair',
      email: 'priya.nair@gmail.com',
      mobile: '9447012345',
      passwordHash: hashPassword('Rider@2026'),
      createdAt: daysAgo(2),
      addresses: [
        {
          id: 'addr-8',
          name: 'Priya Nair',
          mobile: '9447012345',
          house: 'Villa 9, Palm Meadows',
          street: 'Panampilly Nagar',
          city: 'Kochi',
          state: 'Kerala',
          pincode: '682036',
          type: 'Home',
          isDefault: true,
        },
      ],
    },
    {
      id: 'usr-109',
      name: 'Tanmay Joshi',
      email: 'tanmay.j@gmail.com',
      mobile: '9822001122',
      passwordHash: hashPassword('Rider@2026'),
      createdAt: daysAgo(1),
      addresses: [
        {
          id: 'addr-9',
          name: 'Tanmay Joshi',
          mobile: '9822001122',
          house: 'Flat 101, Surya Heights',
          street: 'Civil Lines',
          city: 'Nagpur',
          state: 'Maharashtra',
          pincode: '440001',
          type: 'Home',
          isDefault: true,
        },
      ],
    },
    {
      id: 'usr-110',
      name: 'Aditya Roy',
      email: 'aditya.roy@gmail.com',
      mobile: '9830099887',
      passwordHash: hashPassword('Rider@2026'),
      createdAt: daysAgo(1),
      addresses: [
        {
          id: 'addr-10',
          name: 'Aditya Roy',
          mobile: '9830099887',
          house: '24/1, Ballygunge Circular Rd',
          street: 'Ballygunge',
          city: 'Kolkata',
          state: 'West Bengal',
          pincode: '700019',
          type: 'Home',
          isDefault: true,
        },
      ],
    },
    {
      id: 'usr-111',
      name: 'Meera Sundaram',
      email: 'meera.s@gmail.com',
      mobile: '9444055667',
      passwordHash: hashPassword('Rider@2026'),
      createdAt: daysAgo(0, 8, 15), // Today 08:15 AM
      addresses: [
        {
          id: 'addr-11',
          name: 'Meera Sundaram',
          mobile: '9444055667',
          house: 'Old 45, Anna Salai',
          street: 'T. Nagar',
          city: 'Chennai',
          state: 'Tamil Nadu',
          pincode: '600017',
          type: 'Home',
          isDefault: true,
        },
      ],
    },
    {
      id: 'usr-112',
      name: 'Siddharth Rao',
      email: 'siddharth.r@gmail.com',
      mobile: '9849011223',
      passwordHash: hashPassword('Rider@2026'),
      createdAt: daysAgo(0, 14, 20), // Today 02:20 PM
      addresses: [
        {
          id: 'addr-12',
          name: 'Siddharth Rao',
          mobile: '9849011223',
          house: 'Plot 302, Road No. 36',
          street: 'Jubilee Hills',
          city: 'Hyderabad',
          state: 'Telangana',
          pincode: '500033',
          type: 'Work',
          isDefault: true,
        },
      ],
    },
    // Older Historical Users (Months Ago)
    { id: 'usr-113', name: 'Manish Pandey', email: 'manish.p@gmail.com', mobile: '9810011221', passwordHash: hashPassword('Rider@2026'), createdAt: daysAgo(45), addresses: [] },
    { id: 'usr-114', name: 'Gaurav Kulkarni', email: 'gaurav.k@yahoo.com', mobile: '9820022334', passwordHash: hashPassword('Rider@2026'), createdAt: daysAgo(50), addresses: [] },
    { id: 'usr-115', name: 'Karan Singhania', email: 'karan.s@hotmail.com', mobile: '9830033445', passwordHash: hashPassword('Rider@2026'), createdAt: daysAgo(60), addresses: [] },
    { id: 'usr-116', name: 'Nikhil Mehta', email: 'nikhil.m@gmail.com', mobile: '9840044556', passwordHash: hashPassword('Rider@2026'), createdAt: daysAgo(65), addresses: [] },
    { id: 'usr-117', name: 'Alok Tripathi', email: 'alok.t@gmail.com', mobile: '9850055667', passwordHash: hashPassword('Rider@2026'), createdAt: daysAgo(75), addresses: [] },
    { id: 'usr-118', name: 'Deepak Saxena', email: 'deepak.s@outlook.com', mobile: '9860066778', passwordHash: hashPassword('Rider@2026'), createdAt: daysAgo(85), addresses: [] },
    { id: 'usr-119', name: 'Tarun Bansal', email: 'tarun.b@yahoo.com', mobile: '9870077889', passwordHash: hashPassword('Rider@2026'), createdAt: daysAgo(95), addresses: [] },
    { id: 'usr-120', name: 'Varun Grover', email: 'varun.g@gmail.com', mobile: '9880088990', passwordHash: hashPassword('Rider@2026'), createdAt: daysAgo(105), addresses: [] },
    { id: 'usr-121', name: 'Ashish Nambiar', email: 'ashish.n@gmail.com', mobile: '9890099001', passwordHash: hashPassword('Rider@2026'), createdAt: daysAgo(115), addresses: [] },
    { id: 'usr-122', name: 'Pranav Menon', email: 'pranav.m@gmail.com', mobile: '9811122334', passwordHash: hashPassword('Rider@2026'), createdAt: daysAgo(125), addresses: [] },
    { id: 'usr-123', name: 'Ritesh Agarwal', email: 'ritesh.a@gmail.com', mobile: '9822233445', passwordHash: hashPassword('Rider@2026'), createdAt: daysAgo(135), addresses: [] },
    { id: 'usr-124', name: 'Devendra Joshi', email: 'devendra.j@gmail.com', mobile: '9833344556', passwordHash: hashPassword('Rider@2026'), createdAt: daysAgo(145), addresses: [] },
    { id: 'usr-125', name: 'Harish Roy', email: 'harish.r@gmail.com', mobile: '9844455667', passwordHash: hashPassword('Rider@2026'), createdAt: daysAgo(155), addresses: [] },
    { id: 'usr-126', name: 'Sanjay Dutt', email: 'sanjay.d@gmail.com', mobile: '9855566778', passwordHash: hashPassword('Rider@2026'), createdAt: daysAgo(165), addresses: [] },
    { id: 'usr-127', name: 'Vijay Mallya', email: 'vijay.m@gmail.com', mobile: '9866677889', passwordHash: hashPassword('Rider@2026'), createdAt: daysAgo(175), addresses: [] },
  ];
  UserModel.seedUsers(demoUsers);

  // 2. DEMO PRODUCTS (13 Products)
  const demoProducts = [
    {
      id: 'prod-101',
      name: 'Rynox Air GT Jacket',
      slug: 'rynox-air-gt-jacket',
      type: 'Multiple Variants',
      brand: 'Rynox',
      category: 'Jackets',
      subcategory: 'Riding Jacket',
      tags: ['Touring', 'Summer', 'Protective', 'Best Seller'],
      hsnCode: '6211',
      gstRate: '18%',
      internalSku: 'RYN-AIRGT-2026',
      images: ['/images/jacket.webp', '/images/jackets.webp'],
      shortDescription: 'Premium all-weather mesh riding jacket with Safe-Tech CE Level 2 armor.',
      description: 'Built for long distance touring and daily commuting. Features heavy-duty 600D mesh, CE Level 2 protectors on shoulders, elbows, and back, thermal liner, and high-visibility reflective striping.',
      features: [
        'CE Level 2 armor on shoulders, elbows & back',
        'Heavy duty 600D polyester mesh outer shell',
        'Detachable thermal liner and rain cover included',
        '360-degree high visibility reflective trim',
        'Multiple arm and waist adjustment straps',
      ],
      specifications: {
        jacketType: 'Touring',
        protection: ['Shoulder', 'Elbow', 'Back'],
        protectionCert: 'CE Level 2',
        outerMaterial: 'Textile / Mesh',
        waterproof: 'Water Resistant',
        thermalLiner: 'Removable',
      },
      sizeType: 'Apparel',
      sizes: ['M', 'L', 'XL'],
      colours: ['Black', 'Red'],
      fitType: 'Regular',
      mrp: 6999,
      price: 5999,
      costPrice: 4200,
      discountPercent: 14,
      marginPercent: 30,
      lowStockThreshold: 3,
      reorderLevel: 5,
      warehouseLocation: 'Rack A1 - Shelf 2',
      supplier: 'Rynox India Ltd',
      physicalProduct: true,
      weight: '1.65 kg',
      dimensions: { length: '45', width: '35', height: '15' },
      shippingClass: 'Standard',
      freeShipping: true,
      warrantyType: 'Manufacturer Warranty',
      warrantyDuration: '1 Year',
      warrantyInfo: '1 Year official manufacturer warranty covering zippers and seam defects.',
      whatsIncluded: ['1 × Rynox Air GT Jacket', '1 × CE Level 2 Back Protector', '1 × Detachable Thermal Liner'],
      careInstructions: 'Hand wash with mild detergent. Remove armors before washing.',
      returnEligibility: 'Eligible',
      returnWindow: '10 Days',
      status: 'Active',
      visibility: 'Visible',
      featured: 'Yes',
      internalNotes: 'Popular summer riding jacket. High reorder frequency.',
      publishedAt: daysAgo(40),
      createdAt: daysAgo(40),
      variants: [
        { id: 'var-101-1', colour: 'Black', size: 'M', sku: 'RYN-AGT-BLK-M', price: 5999, costPrice: 4200, stock: 8, location: 'Rack A1', status: 'In Stock' },
        { id: 'var-101-2', colour: 'Black', size: 'L', sku: 'RYN-AGT-BLK-L', price: 5999, costPrice: 4200, stock: 3, location: 'Rack A1', status: 'Low Stock' },
        { id: 'var-101-3', colour: 'Black', size: 'XL', sku: 'RYN-AGT-BLK-XL', price: 5999, costPrice: 4200, stock: 0, location: 'Rack A1', status: 'Sold Out' },
        { id: 'var-101-4', colour: 'Red', size: 'M', sku: 'RYN-AGT-RED-M', price: 5999, costPrice: 4200, stock: 5, location: 'Rack A1', status: 'In Stock' },
        { id: 'var-101-5', colour: 'Red', size: 'L', sku: 'RYN-AGT-RED-L', price: 5999, costPrice: 4200, stock: 4, location: 'Rack A1', status: 'In Stock' },
      ],
      totalStock: 20,
    },
    {
      id: 'prod-102',
      name: 'Axor Apex Superfly Helmet',
      slug: 'axor-apex-superfly-helmet',
      type: 'Multiple Variants',
      brand: 'Axor',
      category: 'Helmets',
      subcategory: 'Full Face',
      tags: ['ECE Certified', 'Dual Visor', 'Aerodynamic'],
      hsnCode: '6506',
      gstRate: '28%',
      internalSku: 'AXO-APEX-2026',
      images: ['/images/helmet.webp', '/images/helmets.webp'],
      shortDescription: 'ECE & DOT certified dual visor helmet with aerodynamic spoiler.',
      description: 'High-performance full face helmet built with ABS shell, Pinlock ready visor, integrated sun shield, and breath deflector.',
      features: ['ECE 22.05 & DOT certified', 'Dual visor system with integrated drop-down sun shield', 'Pinlock 30 anti-fog lens included', 'Removable and washable hypoallergenic cheek pads'],
      specifications: { helmetType: 'Full Face', shellMaterial: 'Polycarbonate / ABS', weight: '1.45 kg', visor: 'Dual Visor', closure: 'Micrometric' },
      sizeType: 'Helmet',
      sizes: ['M', 'L'],
      colours: ['Black', 'Red'],
      mrp: 5494,
      price: 4994,
      costPrice: 3500,
      discountPercent: 9,
      marginPercent: 30,
      lowStockThreshold: 2,
      reorderLevel: 4,
      warehouseLocation: 'Rack B2 - Shelf 1',
      supplier: 'Axor Helmets India',
      physicalProduct: true,
      weight: '1.45 kg',
      dimensions: { length: '38', width: '28', height: '28' },
      shippingClass: 'Standard',
      freeShipping: true,
      warrantyType: 'Manufacturer Warranty',
      warrantyDuration: '2 Years',
      warrantyInfo: '2 Years warranty covering manufacturing defects.',
      whatsIncluded: ['1 × Axor Apex Helmet', '1 × Helmet Bag', '1 × Pinlock Lens'],
      returnEligibility: 'Eligible',
      returnWindow: '10 Days',
      status: 'Active',
      visibility: 'Visible',
      featured: 'Yes',
      publishedAt: daysAgo(35),
      createdAt: daysAgo(35),
      variants: [
        { id: 'var-102-1', colour: 'Black', size: 'M', sku: 'AAS-BLK-M', price: 4994, costPrice: 3500, stock: 6, location: 'Rack B2', status: 'In Stock' },
        { id: 'var-102-2', colour: 'Black', size: 'L', sku: 'AAS-BLK-L', price: 4994, costPrice: 3500, stock: 4, location: 'Rack B2', status: 'In Stock' },
        { id: 'var-102-3', colour: 'Red', size: 'L', sku: 'AAS-RED-L', price: 4994, costPrice: 3500, stock: 2, location: 'Rack B2', status: 'Low Stock' },
      ],
      totalStock: 12,
    },
    {
      id: 'prod-103',
      name: 'Viaterra Claw Tail Bag',
      slug: 'viaterra-claw-tail-bag',
      type: 'Single Variant',
      brand: 'Viaterra',
      category: 'Luggage',
      subcategory: 'Tail Bag',
      tags: ['Luggage', 'Touring', 'Waterproof Inner'],
      hsnCode: '4202',
      gstRate: '18%',
      internalSku: 'VIA-CLAW-70L',
      images: ['/images/luggage.webp'],
      shortDescription: '70L heavy-duty all-terrain tail bag for long distance motorcycle expeditions.',
      description: 'Zero-displacement tail bag designed to fit securely on pillion seats without mounting racks.',
      features: ['70 Litres capacity', 'Includes 100% waterproof seam-sealed dry bag', 'Heavy-duty 1680D Cordura fabric'],
      specifications: { capacity: '70 L' },
      sizeType: 'One Size',
      sizes: ['One Size'],
      colours: ['Black'],
      mrp: 4499,
      price: 3999,
      costPrice: 2800,
      discountPercent: 11,
      marginPercent: 30,
      lowStockThreshold: 3,
      reorderLevel: 5,
      warehouseLocation: 'Rack C1',
      supplier: 'Viaterra Gear',
      physicalProduct: true,
      weight: '2.10 kg',
      dimensions: { length: '60', width: '35', height: '35' },
      shippingClass: 'Standard',
      freeShipping: true,
      warrantyType: 'Manufacturer Warranty',
      warrantyDuration: '1 Year',
      returnEligibility: 'Eligible',
      returnWindow: '10 Days',
      status: 'Active',
      visibility: 'Visible',
      featured: 'No',
      publishedAt: daysAgo(30),
      createdAt: daysAgo(30),
      variants: [
        { id: 'var-103-1', colour: 'Black', size: 'One Size', sku: 'VIA-CLAW-BLK', price: 3999, costPrice: 2800, stock: 12, location: 'Rack C1', status: 'In Stock' },
      ],
      totalStock: 12,
    },
    {
      id: 'prod-104',
      name: 'Rynox Urban Pro Gloves',
      slug: 'rynox-urban-pro-gloves',
      type: 'Multiple Variants',
      brand: 'Rynox',
      category: 'Gloves',
      subcategory: 'Urban',
      tags: ['City Commute', 'Touchscreen Compatible', 'KNOX Slider'],
      hsnCode: '6216',
      gstRate: '18%',
      internalSku: 'RYN-UPG-2026',
      images: ['/images/gloves.webp'],
      shortDescription: 'Short cuff mesh gloves with patented KNOX SPS palm sliders.',
      description: 'Lightweight, breathable urban gloves for daily riding featuring TPR knuckle protectors and capacitive touchscreen tips.',
      features: ['KNOX SPS Palm Sliders', 'TPR Knuckle Protection', 'Touchscreen smart tips'],
      specifications: { touchscreen: 'Yes' },
      sizeType: 'Gloves',
      sizes: ['S', 'M', 'L', 'XL'],
      colours: ['Black'],
      mrp: 2750,
      price: 2499,
      costPrice: 1750,
      discountPercent: 9,
      marginPercent: 30,
      lowStockThreshold: 2,
      reorderLevel: 4,
      warehouseLocation: 'Rack A3',
      supplier: 'Rynox India Ltd',
      physicalProduct: true,
      weight: '0.40 kg',
      dimensions: { length: '25', width: '15', height: '5' },
      shippingClass: 'Standard',
      freeShipping: false,
      returnEligibility: 'Eligible',
      returnWindow: '10 Days',
      status: 'Active',
      visibility: 'Visible',
      featured: 'No',
      publishedAt: daysAgo(28),
      createdAt: daysAgo(28),
      variants: [
        { id: 'var-104-1', colour: 'Black', size: 'S', sku: 'RYN-UPG-BLK-S', price: 2499, costPrice: 1750, stock: 0, location: 'Rack A3', status: 'Sold Out' },
        { id: 'var-104-2', colour: 'Black', size: 'M', sku: 'RYN-UPG-BLK-M', price: 2499, costPrice: 1750, stock: 0, location: 'Rack A3', status: 'Sold Out' },
        { id: 'var-104-3', colour: 'Black', size: 'L', sku: 'RYN-UPG-BLK-L', price: 2499, costPrice: 1750, stock: 0, location: 'Rack A3', status: 'Sold Out' },
        { id: 'var-104-4', colour: 'Black', size: 'XL', sku: 'RYN-UPG-BLK-XL', price: 2499, costPrice: 1750, stock: 0, location: 'Rack A3', status: 'Sold Out' },
      ],
      totalStock: 0, // OUT OF STOCK PRODUCT
    },
    {
      id: 'prod-105',
      name: 'SMK Stellar Sports Helmet',
      slug: 'smk-stellar-sports-helmet',
      type: 'Multiple Variants',
      brand: 'SMK',
      category: 'Helmets',
      subcategory: 'Full Face',
      tags: ['ECE Certified', 'Air Vents'],
      hsnCode: '6506',
      gstRate: '28%',
      internalSku: 'SMK-STL-2026',
      images: ['/images/helmet.webp'],
      shortDescription: 'Aerodynamic full face helmet with quick release visor.',
      description: 'Engineered in Italy. High impact ECE 22.05 approved helmet.',
      features: ['ECE Approved', 'Quick release visor', 'Multi-density EPS liner'],
      specifications: { helmetType: 'Full Face', closure: 'Micrometric' },
      sizeType: 'Helmet',
      sizes: ['M', 'L'],
      colours: ['Black'],
      mrp: 4200,
      price: 3850,
      costPrice: 2700,
      discountPercent: 8,
      marginPercent: 30,
      lowStockThreshold: 2,
      reorderLevel: 4,
      warehouseLocation: 'Rack B1',
      supplier: 'SMK Helmets',
      physicalProduct: true,
      weight: '1.40 kg',
      shippingClass: 'Standard',
      freeShipping: true,
      status: 'Active',
      visibility: 'Visible',
      featured: 'No',
      publishedAt: daysAgo(25),
      createdAt: daysAgo(25),
      variants: [
        { id: 'var-105-1', colour: 'Black', size: 'M', sku: 'SMK-STL-BLK-M', price: 3850, costPrice: 2700, stock: 5, location: 'Rack B1', status: 'In Stock' },
        { id: 'var-105-2', colour: 'Black', size: 'L', sku: 'SMK-STL-BLK-L', price: 3850, costPrice: 2700, stock: 7, location: 'Rack B1', status: 'In Stock' },
      ],
      totalStock: 12,
    },
    {
      id: 'prod-106',
      name: 'Raida RainLock Waterproof Suit',
      slug: 'raida-rainlock-waterproof-suit',
      type: 'Multiple Variants',
      brand: 'Raida',
      category: 'Rainwear',
      subcategory: 'Full Suit',
      tags: ['100% Waterproof', 'Seam Sealed', 'Compact Bag'],
      hsnCode: '6210',
      gstRate: '12%',
      internalSku: 'RAI-RNLK-2026',
      images: ['/images/rainwear.webp'],
      shortDescription: '10,000mm water column rated breathable rain suit with jacket & pants.',
      description: 'Heavy torrential rain protector with sealed seams and foldaway hood.',
      features: ['10,000mm Waterproof rating', 'Dual flap closure', 'Reflective rear logo'],
      specifications: { waterproof: '100% Waterproof' },
      sizeType: 'Apparel',
      sizes: ['M', 'L', 'XL'],
      colours: ['Black'],
      mrp: 2999,
      price: 2499,
      costPrice: 1700,
      discountPercent: 17,
      marginPercent: 32,
      lowStockThreshold: 3,
      reorderLevel: 5,
      warehouseLocation: 'Rack D2',
      supplier: 'Raida Gear',
      physicalProduct: true,
      weight: '0.85 kg',
      shippingClass: 'Standard',
      freeShipping: false,
      status: 'Active',
      visibility: 'Visible',
      featured: 'No',
      publishedAt: daysAgo(22),
      createdAt: daysAgo(22),
      variants: [
        { id: 'var-106-1', colour: 'Black', size: 'M', sku: 'RAI-RLK-BLK-M', price: 2499, costPrice: 1700, stock: 10, location: 'Rack D2', status: 'In Stock' },
        { id: 'var-106-2', colour: 'Black', size: 'L', sku: 'RAI-RLK-BLK-L', price: 2499, costPrice: 1700, stock: 8, location: 'Rack D2', status: 'In Stock' },
        { id: 'var-106-3', colour: 'Black', size: 'XL', sku: 'RAI-RLK-BLK-XL', price: 2499, costPrice: 1700, stock: 4, location: 'Rack D2', status: 'In Stock' },
      ],
      totalStock: 22,
    },
    {
      id: 'prod-107',
      name: 'Motul E9 Wash & Wax Spray',
      slug: 'motul-e9-wash-wax-spray',
      type: 'Single Variant',
      brand: 'Motul',
      category: 'Accessories',
      subcategory: 'Maintenance',
      tags: ['Cleaning', 'Polish', 'Chain Care'],
      hsnCode: '3402',
      gstRate: '18%',
      internalSku: 'MOT-E9-400ML',
      images: ['/images/accessories.webp'],
      shortDescription: 'Dry cleaner and protective wax spray for motorcycle fairings and frame.',
      description: 'Leaves a long-lasting protective non-sticky wax film on surfaces.',
      features: ['Cleans without water', 'Restores shine', 'Protects against dust'],
      specifications: {},
      sizeType: 'One Size',
      sizes: ['One Size'],
      colours: ['Multi'],
      mrp: 650,
      price: 590,
      costPrice: 400,
      discountPercent: 9,
      marginPercent: 32,
      lowStockThreshold: 5,
      reorderLevel: 10,
      warehouseLocation: 'Shelf E1',
      supplier: 'Motul Lubricants',
      physicalProduct: true,
      weight: '0.45 kg',
      shippingClass: 'Standard',
      freeShipping: false,
      status: 'Active',
      visibility: 'Visible',
      featured: 'No',
      publishedAt: daysAgo(20),
      createdAt: daysAgo(20),
      variants: [
        { id: 'var-107-1', colour: 'Multi', size: 'One Size', sku: 'MOT-E9-WW', price: 590, costPrice: 400, stock: 25, location: 'Shelf E1', status: 'In Stock' },
      ],
      totalStock: 25,
    },
    {
      id: 'prod-108',
      name: 'Rynox Advento Riding Pants',
      slug: 'rynox-advento-riding-pants',
      type: 'Multiple Variants',
      brand: 'Rynox',
      category: 'Pants',
      subcategory: 'Adventure',
      tags: ['CE Armor', 'Ventilated', 'Waterproof Liner'],
      hsnCode: '6211',
      gstRate: '18%',
      internalSku: 'RYN-ADV-PNT',
      images: ['/images/pants.webp'],
      shortDescription: 'All-season touring riding trousers with Knox knee armor.',
      description: 'Ergonomically designed adventure pants with accordion stretch panels.',
      features: ['Knox Flexiform CE knee armor', 'Aero-mesh ventilation panels'],
      specifications: {},
      sizeType: 'Apparel',
      sizes: ['M', 'L', 'XL'],
      colours: ['Black'],
      mrp: 6500,
      price: 5750,
      costPrice: 4000,
      discountPercent: 12,
      marginPercent: 30,
      lowStockThreshold: 2,
      reorderLevel: 4,
      warehouseLocation: 'Rack A2',
      supplier: 'Rynox India Ltd',
      physicalProduct: true,
      weight: '1.30 kg',
      shippingClass: 'Standard',
      freeShipping: true,
      status: 'Active',
      visibility: 'Visible',
      featured: 'No',
      publishedAt: daysAgo(18),
      createdAt: daysAgo(18),
      variants: [
        { id: 'var-108-1', colour: 'Black', size: 'M', sku: 'RYN-ADV-BLK-M', price: 5750, costPrice: 4000, stock: 4, location: 'Rack A2', status: 'In Stock' },
        { id: 'var-108-2', colour: 'Black', size: 'L', sku: 'RYN-ADV-BLK-L', price: 5750, costPrice: 4000, stock: 2, location: 'Rack A2', status: 'Low Stock' },
        { id: 'var-108-3', colour: 'Black', size: 'XL', sku: 'RYN-ADV-BLK-XL', price: 5750, costPrice: 4000, stock: 1, location: 'Rack A2', status: 'Low Stock' },
      ],
      totalStock: 7,
    },
    {
      id: 'prod-109',
      name: 'Scala Trekker Boots',
      slug: 'scala-trekker-boots',
      type: 'Multiple Variants',
      brand: 'Scala',
      category: 'Boots',
      subcategory: 'Touring',
      tags: ['CE Certified', 'Leather', 'Waterproof'],
      hsnCode: '6403',
      gstRate: '18%',
      internalSku: 'SCA-TRK-BOOTS',
      images: ['/images/boots.webp'],
      shortDescription: 'Full grain leather waterproof touring motorcycle boots.',
      description: 'Reinforced heel, toe cap and ankle disc protection.',
      features: ['Full Grain Leather construction', 'Hipora waterproof membrane'],
      specifications: {},
      sizeType: 'Footwear',
      sizes: ['41', '42', '43'],
      colours: ['Black'],
      mrp: 7999,
      price: 7200,
      costPrice: 5000,
      discountPercent: 10,
      marginPercent: 31,
      lowStockThreshold: 2,
      reorderLevel: 3,
      warehouseLocation: 'Rack D1',
      supplier: 'Scala Gears',
      physicalProduct: true,
      weight: '1.90 kg',
      shippingClass: 'Standard',
      freeShipping: true,
      status: 'Active',
      visibility: 'Visible',
      featured: 'No',
      publishedAt: daysAgo(15),
      createdAt: daysAgo(15),
      variants: [
        { id: 'var-109-1', colour: 'Black', size: '41', sku: 'SCA-TRK-BLK-41', price: 7200, costPrice: 5000, stock: 3, location: 'Rack D1', status: 'In Stock' },
        { id: 'var-109-2', colour: 'Black', size: '42', sku: 'SCA-TRK-BLK-42', price: 7200, costPrice: 5000, stock: 0, location: 'Rack D1', status: 'Sold Out' },
        { id: 'var-109-3', colour: 'Black', size: '43', sku: 'SCA-TRK-BLK-43', price: 7200, costPrice: 5000, stock: 2, location: 'Rack D1', status: 'Low Stock' },
      ],
      totalStock: 5,
    },
    {
      id: 'prod-110',
      name: 'Motorradical Aluminium Top Case 45L',
      slug: 'motorradical-aluminium-top-case-45l',
      type: 'Single Variant',
      brand: 'Motorradical',
      category: 'Luggage',
      subcategory: 'Top Box',
      tags: ['Heavy Duty', 'Lockable', 'Aluminium'],
      hsnCode: '4202',
      gstRate: '28%',
      internalSku: 'MR-ALU-45L',
      images: ['/images/luggage.webp'],
      shortDescription: 'Premium 45L aircraft-grade aluminium top case for adventure tourers.',
      description: 'Stainless steel latch lock mechanism with silicone seal gasket.',
      features: ['45 Litres capacity', '2.0mm aircraft grade aluminium construction'],
      specifications: { capacity: '45 L' },
      sizeType: 'One Size',
      sizes: ['One Size'],
      colours: ['Silver'],
      mrp: 26999,
      price: 24500,
      costPrice: 17500,
      discountPercent: 9,
      marginPercent: 29,
      lowStockThreshold: 1,
      reorderLevel: 2,
      warehouseLocation: 'Rack C3',
      supplier: 'Motorradical SA',
      physicalProduct: true,
      weight: '5.80 kg',
      shippingClass: 'Bulky / Heavy',
      freeShipping: true,
      status: 'Active',
      visibility: 'Visible',
      featured: 'Yes',
      publishedAt: daysAgo(10),
      createdAt: daysAgo(10),
      variants: [
        { id: 'var-110-1', colour: 'Silver', size: 'One Size', sku: 'MR-ALU-45L-SLV', price: 24500, costPrice: 17500, stock: 1, location: 'Rack C3', status: 'Low Stock' },
      ],
      totalStock: 1, // LOW STOCK PRODUCT
    },
    {
      id: 'prod-111',
      name: 'Mototrek Pro Touring Knee Guards',
      slug: 'mototrek-pro-touring-knee-guards',
      type: 'Single Variant',
      brand: 'Mototrek',
      category: 'Accessories',
      subcategory: 'Maintenance',
      tags: ['Bionic Joint', 'CE Level 2'],
      hsnCode: '6211',
      gstRate: '18%',
      internalSku: 'MTK-KNEE-PRO',
      images: ['/images/accessories.webp'],
      shortDescription: 'Articulated dual-pivot bionic knee and shin protector guards.',
      description: 'Dual hinge system moves naturally with leg motion.',
      features: ['Dual hinge articulation', 'CE Level 2 certified padding'],
      specifications: {},
      sizeType: 'One Size',
      sizes: ['One Size'],
      colours: ['Black'],
      mrp: 3500,
      price: 2999,
      costPrice: 2000,
      discountPercent: 14,
      marginPercent: 33,
      lowStockThreshold: 3,
      reorderLevel: 5,
      warehouseLocation: 'Rack E2',
      supplier: 'Mototrek In-House',
      physicalProduct: true,
      weight: '0.90 kg',
      shippingClass: 'Standard',
      freeShipping: false,
      status: 'Draft', // DRAFT PRODUCT
      visibility: 'Hidden',
      featured: 'No',
      internalNotes: 'Sample under QA testing before launching to catalogue.',
      publishedAt: null,
      createdAt: daysAgo(5),
      variants: [
        { id: 'var-111-1', colour: 'Black', size: 'One Size', sku: 'MTK-KNEE-BLK', price: 2999, costPrice: 2000, stock: 10, location: 'Rack E2', status: 'In Stock' },
      ],
      totalStock: 10,
    },
    {
      id: 'prod-112',
      name: 'Steelbird Air SA-2 Helmet',
      slug: 'steelbird-air-sa-2-helmet',
      type: 'Single Variant',
      brand: 'Steelbird',
      category: 'Helmets',
      subcategory: 'Full Face',
      tags: ['ISI Certified'],
      hsnCode: '6506',
      gstRate: '18%',
      internalSku: 'STB-SA2-2026',
      images: ['/images/helmet.webp'],
      shortDescription: 'ISI certified everyday street riding helmet.',
      description: 'Budget commuter helmet with quick release buckle.',
      features: ['ISI Approved'],
      specifications: { helmetType: 'Full Face' },
      sizeType: 'Helmet',
      sizes: ['L'],
      colours: ['Black'],
      mrp: 2499,
      price: 2199,
      costPrice: 1500,
      discountPercent: 12,
      marginPercent: 31,
      status: 'Archived', // DISABLED / UNPUBLISHED PRODUCT
      visibility: 'Hidden',
      featured: 'No',
      publishedAt: null,
      createdAt: daysAgo(40),
      variants: [
        { id: 'var-112-1', colour: 'Black', size: 'L', sku: 'STB-SA2-BLK-L', price: 2199, costPrice: 1500, stock: 0, location: 'Rack B3', status: 'Sold Out' },
      ],
      totalStock: 0,
    },
    {
      id: 'prod-113',
      name: 'Viaterra Fly Magnetic Tank Bag',
      slug: 'viaterra-fly-magnetic-tank-bag',
      type: 'Single Variant',
      brand: 'Viaterra',
      category: 'Luggage',
      subcategory: 'Tank Bag',
      tags: ['Magnetic Mount', 'Clear Phone Pocket'],
      hsnCode: '4202',
      gstRate: '18%',
      internalSku: 'VIA-FLY-18L',
      images: ['/images/luggage.webp'],
      shortDescription: '18L expandable magnetic tank bag with touch sensitive phone window.',
      description: 'Rare earth neodymium magnets hold firm at highway speeds.',
      features: ['Neodymium magnets', 'Touchscreen phone window', 'Rain cover included'],
      specifications: { capacity: '18 L' },
      sizeType: 'One Size',
      sizes: ['One Size'],
      colours: ['Black'],
      mrp: 3899,
      price: 3499,
      costPrice: 2400,
      discountPercent: 10,
      marginPercent: 31,
      lowStockThreshold: 2,
      reorderLevel: 4,
      warehouseLocation: 'Rack C2',
      supplier: 'Viaterra Gear',
      physicalProduct: true,
      weight: '1.20 kg',
      shippingClass: 'Standard',
      freeShipping: true,
      status: 'Active',
      visibility: 'Visible',
      featured: 'No',
      publishedAt: daysAgo(14),
      createdAt: daysAgo(14),
      variants: [
        { id: 'var-113-1', colour: 'Black', size: 'One Size', sku: 'VIA-FLY-BLK', price: 3499, costPrice: 2400, stock: 9, location: 'Rack C2', status: 'In Stock' },
      ],
      totalStock: 9,
    },
  ];
  ProductModel.seedProducts(demoProducts);

  // 3. DEMO COUPONS (6 Coupons)
  const demoCoupons = [
    { id: 'c-101', code: 'MOTOTREK10', type: 'Percentage', discount: 10, minOrder: 3000, usageLimit: 500, timesUsed: 48, status: 'Active', startDate: '2026-01-01', endDate: '2026-12-31' },
    { id: 'c-102', code: 'PUNE200', type: 'Fixed', discount: 200, minOrder: 2000, usageLimit: 200, timesUsed: 95, status: 'Active', startDate: '2026-01-01', endDate: '2026-12-31' },
    { id: 'c-103', code: 'RIDE500', type: 'Fixed', discount: 500, minOrder: 5000, usageLimit: 100, timesUsed: 34, status: 'Active', startDate: '2026-02-01', endDate: '2026-12-31' },
    { id: 'c-104', code: 'WELCOME10', type: 'Percentage', discount: 10, minOrder: 1500, usageLimit: 1000, timesUsed: 120, status: 'Active', startDate: '2026-01-01', endDate: '2026-12-31' },
    { id: 'c-105', code: 'GEAR15', type: 'Percentage', discount: 15, minOrder: 6000, usageLimit: 50, timesUsed: 18, status: 'Active', startDate: '2026-03-01', endDate: '2026-12-31' },
    { id: 'c-106', code: 'SUMMER20', type: 'Percentage', discount: 20, minOrder: 4000, usageLimit: 50, timesUsed: 50, status: 'Expired', startDate: '2026-04-01', endDate: '2026-06-30' },
  ];
  CouponModel.seedCoupons(demoCoupons);

  // 4. DEMO ORDERS (16 Relational Orders MTK-1001 to MTK-1016)
  const demoOrders = [
    {
      id: 'MTK-1001',
      customerId: 'usr-101',
      customerName: 'Rahul Sharma',
      email: 'rahul.s@gmail.com',
      mobile: '9823011234',
      shippingAddress: { name: 'Rahul Sharma', house: 'Flat 402, Royal Palms', street: 'Baner Road', city: 'Pune', state: 'Maharashtra', pincode: '411045' },
      items: [
        { productId: 'prod-101', name: 'Rynox Air GT Jacket', brand: 'Rynox', colour: 'Black', size: 'L', sku: 'RYN-AGT-BLK-L', price: 5999, quantity: 1 },
        { productId: 'prod-104', name: 'Rynox Urban Pro Gloves', brand: 'Rynox', colour: 'Black', size: 'L', sku: 'RYN-UPG-BLK-L', price: 2499, quantity: 1 },
      ],
      subtotal: 8498,
      discount: 500,
      couponApplied: 'RIDE500',
      shippingFee: 0,
      grandTotal: 7998,
      paymentMethod: 'Razorpay (UPI)',
      paymentStatus: 'Paid',
      transactionId: 'pay_RZP882910',
      paymentLink: 'https://razorpay.com/pay/demo_mtk1001',
      orderStatus: 'Delivered',
      awb: 'BD94810234IN',
      courier: 'BlueDart Express',
      dispatchedAt: daysAgo(13),
      estimatedDelivery: daysAgo(12),
      deliveredAt: daysAgo(12),
      createdAt: daysAgo(15),
      statusHistory: [
        { status: 'Order Placed', timestamp: daysAgo(15) },
        { status: 'Order Confirmed', timestamp: daysAgo(15, 10, 45) },
        { status: 'Processing', timestamp: daysAgo(14, 11, 0) },
        { status: 'Packed', timestamp: daysAgo(14, 15, 30) },
        { status: 'Shipped', timestamp: daysAgo(13, 09, 0) },
        { status: 'Out for Delivery', timestamp: daysAgo(12, 08, 30) },
        { status: 'Delivered', timestamp: daysAgo(12, 14, 15) },
      ],
    },
    {
      id: 'MTK-1002',
      customerId: 'usr-102',
      customerName: 'Vikram Patel',
      email: 'vikram.patel@yahoo.com',
      mobile: '9890123456',
      shippingAddress: { name: 'Vikram Patel', house: '12B, Sea Crest Towers', street: 'Marine Drive', city: 'Mumbai', state: 'Maharashtra', pincode: '400020' },
      items: [
        { productId: 'prod-102', name: 'Axor Apex Superfly Helmet', brand: 'Axor', colour: 'Black', size: 'L', sku: 'AAS-BLK-L', price: 4994, quantity: 1 },
      ],
      subtotal: 4994,
      discount: 0,
      shippingFee: 0,
      grandTotal: 4994,
      paymentMethod: 'Razorpay (NetBanking)',
      paymentStatus: 'Paid',
      orderStatus: 'Shipped',
      awb: 'DL88392011IN',
      courier: 'Delhivery Logistics',
      createdAt: daysAgo(5),
      statusHistory: [
        { status: 'Order Placed', timestamp: daysAgo(5) },
        { status: 'Order Confirmed', timestamp: daysAgo(5, 11, 0) },
        { status: 'Processing', timestamp: daysAgo(4, 09, 30) },
        { status: 'Packed', timestamp: daysAgo(4, 16, 0) },
        { status: 'Shipped', timestamp: daysAgo(3, 10, 15) },
      ],
    },
    {
      id: 'MTK-1003',
      customerId: 'usr-103',
      customerName: 'Ananya Iyer',
      email: 'ananya.i@gmail.com',
      mobile: '9845098765',
      shippingAddress: { name: 'Ananya Iyer', house: '#45, 10th Main', street: 'Indiranagar', city: 'Bengaluru', state: 'Karnataka', pincode: '560038' },
      items: [
        { productId: 'prod-103', name: 'Viaterra Claw Tail Bag', brand: 'Viaterra', colour: 'Black', size: 'One Size', sku: 'VIA-CLAW-BLK', price: 3999, quantity: 1 },
        { productId: 'prod-107', name: 'Motul E9 Wash & Wax Spray', brand: 'Motul', colour: 'Multi', size: 'One Size', sku: 'MOT-E9-WW', price: 590, quantity: 1 },
      ],
      subtotal: 4589,
      discount: 459,
      couponApplied: 'MOTOTREK10',
      shippingFee: 0,
      grandTotal: 4130,
      paymentMethod: 'Razorpay (Card)',
      paymentStatus: 'Paid',
      orderStatus: 'Processing',
      createdAt: daysAgo(3),
      statusHistory: [
        { status: 'Order Placed', timestamp: daysAgo(3) },
        { status: 'Order Confirmed', timestamp: daysAgo(3, 11, 30) },
        { status: 'Processing', timestamp: daysAgo(2, 10, 0) },
      ],
    },
    {
      id: 'MTK-1004',
      customerId: 'usr-104',
      customerName: 'Amit Verma',
      email: 'amit.v@hotmail.com',
      mobile: '9811223344',
      shippingAddress: { name: 'Amit Verma', house: 'C-14, Vasant Kunj', street: 'Nelson Mandela Marg', city: 'New Delhi', state: 'Delhi', pincode: '110070' },
      items: [
        { productId: 'prod-106', name: 'Raida RainLock Waterproof Suit', brand: 'Raida', colour: 'Black', size: 'L', sku: 'RAI-RLK-BLK-L', price: 2499, quantity: 1 },
      ],
      subtotal: 2499,
      discount: 200,
      couponApplied: 'PUNE200',
      shippingFee: 150,
      grandTotal: 2449,
      paymentMethod: 'Cash on Delivery (COD)',
      paymentStatus: 'Pending',
      orderStatus: 'Packed',
      createdAt: daysAgo(2),
      statusHistory: [
        { status: 'Order Placed', timestamp: daysAgo(2) },
        { status: 'Order Confirmed', timestamp: daysAgo(2, 12, 0) },
        { status: 'Processing', timestamp: daysAgo(1, 09, 0) },
        { status: 'Packed', timestamp: daysAgo(1, 15, 30) },
      ],
    },
    {
      id: 'MTK-1005',
      customerId: 'usr-105',
      customerName: 'Rohan Deshmukh',
      email: 'rohan.d@gmail.com',
      mobile: '9765432109',
      shippingAddress: { name: 'Rohan Deshmukh', house: 'B-201, Green Acres', street: 'Kothrud', city: 'Pune', state: 'Maharashtra', pincode: '411038' },
      items: [
        { productId: 'prod-108', name: 'Rynox Advento Riding Pants', brand: 'Rynox', colour: 'Black', size: 'M', sku: 'RYN-ADV-BLK-M', price: 5750, quantity: 1 },
      ],
      subtotal: 5750,
      discount: 0,
      shippingFee: 0,
      grandTotal: 5750,
      paymentMethod: 'Razorpay (UPI)',
      paymentStatus: 'Paid',
      orderStatus: 'Order Placed',
      createdAt: daysAgo(1), // Yesterday
      statusHistory: [
        { status: 'Order Placed', timestamp: daysAgo(1) },
        { status: 'Order Confirmed', timestamp: daysAgo(1, 11, 0) },
      ],
    },
    {
      id: 'MTK-1006',
      customerId: 'usr-106',
      customerName: 'Sneha Kulkarni',
      email: 'sneha.k@gmail.com',
      mobile: '9922334455',
      shippingAddress: { name: 'Sneha Kulkarni', house: 'Plot 78, College Road', street: 'Gangapur Road', city: 'Nashik', state: 'Maharashtra', pincode: '422005' },
      items: [
        { productId: 'prod-105', name: 'SMK Stellar Sports Helmet', brand: 'SMK', colour: 'Black', size: 'M', sku: 'SMK-STL-BLK-M', price: 3850, quantity: 1 },
      ],
      subtotal: 3850,
      discount: 0,
      shippingFee: 0,
      grandTotal: 3850,
      paymentMethod: 'Razorpay (UPI)',
      paymentStatus: 'Paid',
      orderStatus: 'Order Placed',
      createdAt: daysAgo(0, 9, 30), // Today 09:30 AM
      statusHistory: [
        { status: 'Order Placed', timestamp: daysAgo(0, 9, 30) },
        { status: 'Order Confirmed', timestamp: daysAgo(0, 9, 32) },
      ],
    },
    {
      id: 'MTK-1007',
      customerId: 'usr-107',
      customerName: 'Kabir Malhotra',
      email: 'kabir.m@outlook.com',
      mobile: '9876543210',
      shippingAddress: { name: 'Kabir Malhotra', house: 'House 512, Sector 17', street: 'Madhya Marg', city: 'Chandigarh', state: 'Punjab', pincode: '160017' },
      items: [
        { productId: 'prod-109', name: 'Scala Trekker Boots', brand: 'Scala', colour: 'Black', size: '41', sku: 'SCA-TRK-BLK-41', price: 7200, quantity: 1 },
      ],
      subtotal: 7200,
      discount: 500,
      couponApplied: 'RIDE500',
      shippingFee: 0,
      grandTotal: 6700,
      paymentMethod: 'Razorpay (Card)',
      paymentStatus: 'Paid',
      orderStatus: 'Order Placed',
      createdAt: daysAgo(0, 11, 15), // Today 11:15 AM
      statusHistory: [
        { status: 'Order Placed', timestamp: daysAgo(0, 11, 15) },
        { status: 'Order Confirmed', timestamp: daysAgo(0, 11, 17) },
      ],
    },
    {
      id: 'MTK-1008',
      customerId: 'usr-108',
      customerName: 'Priya Nair',
      email: 'priya.nair@gmail.com',
      mobile: '9447012345',
      shippingAddress: { name: 'Priya Nair', house: 'Villa 9, Palm Meadows', street: 'Panampilly Nagar', city: 'Kochi', state: 'Kerala', pincode: '682036' },
      items: [
        { productId: 'prod-101', name: 'Rynox Air GT Jacket', brand: 'Rynox', colour: 'Black', size: 'M', sku: 'RYN-AGT-BLK-M', price: 5999, quantity: 1 },
      ],
      subtotal: 5999,
      discount: 0,
      shippingFee: 0,
      grandTotal: 5999,
      paymentMethod: 'Razorpay (NetBanking)',
      paymentStatus: 'Failed',
      orderStatus: 'Cancelled',
      createdAt: daysAgo(1, 16, 45),
      statusHistory: [
        { status: 'Order Placed', timestamp: daysAgo(1, 16, 45) },
        { status: 'Cancelled', timestamp: daysAgo(1, 16, 50) },
      ],
    },
    {
      id: 'MTK-1009',
      customerId: 'usr-109',
      customerName: 'Tanmay Joshi',
      email: 'tanmay.j@gmail.com',
      mobile: '9822001122',
      shippingAddress: { name: 'Tanmay Joshi', house: 'Flat 101, Surya Heights', street: 'Civil Lines', city: 'Nagpur', state: 'Maharashtra', pincode: '440001' },
      items: [
        { productId: 'prod-113', name: 'Viaterra Fly Magnetic Tank Bag', brand: 'Viaterra', colour: 'Black', size: 'One Size', sku: 'VIA-FLY-BLK', price: 3499, quantity: 1 },
      ],
      subtotal: 3499,
      discount: 0,
      shippingFee: 0,
      grandTotal: 3499,
      paymentMethod: 'Razorpay (UPI)',
      paymentStatus: 'Paid',
      orderStatus: 'Shipped',
      awb: 'BD77109283IN',
      courier: 'BlueDart Express',
      createdAt: daysAgo(4),
      statusHistory: [
        { status: 'Order Placed', timestamp: daysAgo(4) },
        { status: 'Order Confirmed', timestamp: daysAgo(4, 10, 0) },
        { status: 'Shipped', timestamp: daysAgo(3, 14, 0) },
      ],
    },
    {
      id: 'MTK-1010',
      customerId: 'usr-110',
      customerName: 'Aditya Roy',
      email: 'aditya.roy@gmail.com',
      mobile: '9830099887',
      shippingAddress: { name: 'Aditya Roy', house: '24/1, Ballygunge Circular Rd', street: 'Ballygunge', city: 'Kolkata', state: 'West Bengal', pincode: '700019' },
      items: [
        { productId: 'prod-110', name: 'Motorradical Aluminium Top Case 45L', brand: 'Motorradical', colour: 'Silver', size: 'One Size', sku: 'MR-ALU-45L-SLV', price: 24500, quantity: 1 },
      ],
      subtotal: 24500,
      discount: 0,
      shippingFee: 0,
      grandTotal: 24500,
      paymentMethod: 'Razorpay (Card)',
      paymentStatus: 'Paid',
      orderStatus: 'Delivered',
      awb: 'DL10293847IN',
      courier: 'Delhivery Logistics',
      createdAt: daysAgo(10),
      statusHistory: [
        { status: 'Order Placed', timestamp: daysAgo(10) },
        { status: 'Order Confirmed', timestamp: daysAgo(10, 12, 0) },
        { status: 'Shipped', timestamp: daysAgo(8, 09, 0) },
        { status: 'Delivered', timestamp: daysAgo(6, 16, 0) },
      ],
    },
    {
      id: 'MTK-1011',
      customerId: 'usr-101',
      customerName: 'Rahul Sharma',
      email: 'rahul.s@gmail.com',
      mobile: '9823011234',
      shippingAddress: { name: 'Rahul Sharma', house: 'Flat 402, Royal Palms', street: 'Baner Road', city: 'Pune', state: 'Maharashtra', pincode: '411045' },
      items: [
        { productId: 'prod-107', name: 'Motul E9 Wash & Wax Spray', brand: 'Motul', colour: 'Multi', size: 'One Size', sku: 'MOT-E9-WW', price: 590, quantity: 2 },
      ],
      subtotal: 1180,
      discount: 0,
      shippingFee: 150,
      grandTotal: 1330,
      paymentMethod: 'Razorpay (UPI)',
      paymentStatus: 'Paid',
      orderStatus: 'Delivered',
      awb: 'BD55443322IN',
      courier: 'BlueDart Express',
      createdAt: daysAgo(8),
      statusHistory: [
        { status: 'Order Placed', timestamp: daysAgo(8) },
        { status: 'Delivered', timestamp: daysAgo(5, 14, 0) },
      ],
    },
    {
      id: 'MTK-1012',
      customerId: 'usr-102',
      customerName: 'Vikram Patel',
      email: 'vikram.patel@yahoo.com',
      mobile: '9890123456',
      shippingAddress: { name: 'Vikram Patel', house: '12B, Sea Crest Towers', street: 'Marine Drive', city: 'Mumbai', state: 'Maharashtra', pincode: '400020' },
      items: [
        { productId: 'prod-106', name: 'Raida RainLock Waterproof Suit', brand: 'Raida', colour: 'Black', size: 'XL', sku: 'RAI-RLK-BLK-XL', price: 2499, quantity: 1 },
      ],
      subtotal: 2499,
      discount: 0,
      shippingFee: 150,
      grandTotal: 2649,
      paymentMethod: 'Cash on Delivery (COD)',
      paymentStatus: 'Paid',
      orderStatus: 'Delivered',
      awb: 'DL99887766IN',
      courier: 'Delhivery Logistics',
      createdAt: daysAgo(12),
      statusHistory: [
        { status: 'Order Placed', timestamp: daysAgo(12) },
        { status: 'Delivered', timestamp: daysAgo(9, 11, 0) },
      ],
    },
    // Older Historical Orders (Months Ago)
    { id: 'MTK-1013', customerId: 'usr-113', customerName: 'Manish Pandey', email: 'manish.p@gmail.com', mobile: '9810011221', items: [{ productId: 'prod-101', name: 'Rynox Air GT Jacket', price: 5999, quantity: 1 }], subtotal: 5999, grandTotal: 5999, paymentMethod: 'Razorpay', paymentStatus: 'Paid', orderStatus: 'Delivered', createdAt: daysAgo(45) },
    { id: 'MTK-1014', customerId: 'usr-114', customerName: 'Gaurav Kulkarni', email: 'gaurav.k@yahoo.com', mobile: '9820022334', items: [{ productId: 'prod-102', name: 'Viaterra Fly Tank Bag', price: 2699, quantity: 1 }], subtotal: 2699, grandTotal: 2699, paymentMethod: 'Razorpay', paymentStatus: 'Paid', orderStatus: 'Delivered', createdAt: daysAgo(50) },
    { id: 'MTK-1015', customerId: 'usr-115', customerName: 'Karan Singhania', email: 'karan.s@hotmail.com', mobile: '9830033445', items: [{ productId: 'prod-103', name: 'Mototrek Pro Knee Guards', price: 3499, quantity: 1 }], subtotal: 3499, grandTotal: 3499, paymentMethod: 'Razorpay', paymentStatus: 'Paid', orderStatus: 'Delivered', createdAt: daysAgo(60) },
    { id: 'MTK-1016', customerId: 'usr-116', customerName: 'Nikhil Mehta', email: 'nikhil.m@gmail.com', mobile: '9840044556', items: [{ productId: 'prod-110', name: 'Motorradical 45L Top Case', price: 24999, quantity: 1 }], subtotal: 24999, grandTotal: 24999, paymentMethod: 'Razorpay', paymentStatus: 'Paid', orderStatus: 'Delivered', createdAt: daysAgo(65) },
    { id: 'MTK-1017', customerId: 'usr-117', customerName: 'Alok Tripathi', email: 'alok.t@gmail.com', mobile: '9850055667', items: [{ productId: 'prod-109', name: 'Scala Trekker Boots', price: 6499, quantity: 1 }], subtotal: 6499, grandTotal: 6499, paymentMethod: 'Razorpay', paymentStatus: 'Paid', orderStatus: 'Delivered', createdAt: daysAgo(75) },
    { id: 'MTK-1018', customerId: 'usr-118', customerName: 'Deepak Saxena', email: 'deepak.s@outlook.com', mobile: '9860066778', items: [{ productId: 'prod-108', name: 'Rynox Advento Pants', price: 4999, quantity: 1 }], subtotal: 4999, grandTotal: 4999, paymentMethod: 'Razorpay', paymentStatus: 'Paid', orderStatus: 'Delivered', createdAt: daysAgo(85) },
    { id: 'MTK-1019', customerId: 'usr-119', customerName: 'Tarun Bansal', email: 'tarun.b@yahoo.com', mobile: '9870077889', items: [{ productId: 'prod-105', name: 'SMK Stellar Helmet', price: 4950, quantity: 1 }], subtotal: 4950, grandTotal: 4950, paymentMethod: 'Razorpay', paymentStatus: 'Paid', orderStatus: 'Delivered', createdAt: daysAgo(95) },
    { id: 'MTK-1020', customerId: 'usr-120', customerName: 'Varun Grover', email: 'varun.g@gmail.com', mobile: '9880088990', items: [{ productId: 'prod-106', name: 'Raida RainLock Suit', price: 2499, quantity: 1 }], subtotal: 2499, grandTotal: 2499, paymentMethod: 'Razorpay', paymentStatus: 'Paid', orderStatus: 'Delivered', createdAt: daysAgo(105) },
    { id: 'MTK-1021', customerId: 'usr-121', customerName: 'Ashish Nambiar', email: 'ashish.n@gmail.com', mobile: '9890099001', items: [{ productId: 'prod-101', name: 'Rynox Air GT Jacket', price: 5999, quantity: 1 }], subtotal: 5999, grandTotal: 5999, paymentMethod: 'Razorpay', paymentStatus: 'Paid', orderStatus: 'Delivered', createdAt: daysAgo(115) },
    { id: 'MTK-1022', customerId: 'usr-122', customerName: 'Pranav Menon', email: 'pranav.m@gmail.com', mobile: '9811122334', items: [{ productId: 'prod-102', name: 'Viaterra Fly Tank Bag', price: 2699, quantity: 1 }], subtotal: 2699, grandTotal: 2699, paymentMethod: 'Razorpay', paymentStatus: 'Paid', orderStatus: 'Delivered', createdAt: daysAgo(125) },
    { id: 'MTK-1023', customerId: 'usr-123', customerName: 'Ritesh Agarwal', email: 'ritesh.a@gmail.com', mobile: '9822233445', items: [{ productId: 'prod-103', name: 'Mototrek Pro Knee Guards', price: 3499, quantity: 1 }], subtotal: 3499, grandTotal: 3499, paymentMethod: 'Razorpay', paymentStatus: 'Paid', orderStatus: 'Delivered', createdAt: daysAgo(135) },
    { id: 'MTK-1024', customerId: 'usr-124', customerName: 'Devendra Joshi', email: 'devendra.j@gmail.com', mobile: '9833344556', items: [{ productId: 'prod-109', name: 'Scala Trekker Boots', price: 6499, quantity: 1 }], subtotal: 6499, grandTotal: 6499, paymentMethod: 'Razorpay', paymentStatus: 'Paid', orderStatus: 'Delivered', createdAt: daysAgo(145) },
    { id: 'MTK-1025', customerId: 'usr-125', customerName: 'Harish Roy', email: 'harish.r@gmail.com', mobile: '9844455667', items: [{ productId: 'prod-108', name: 'Rynox Advento Pants', price: 4999, quantity: 1 }], subtotal: 4999, grandTotal: 4999, paymentMethod: 'Razorpay', paymentStatus: 'Paid', orderStatus: 'Delivered', createdAt: daysAgo(155) },
    { id: 'MTK-1026', customerId: 'usr-126', customerName: 'Sanjay Dutt', email: 'sanjay.d@gmail.com', mobile: '9855566778', items: [{ productId: 'prod-105', name: 'SMK Stellar Helmet', price: 4950, quantity: 1 }], subtotal: 4950, grandTotal: 4950, paymentMethod: 'Razorpay', paymentStatus: 'Paid', orderStatus: 'Delivered', createdAt: daysAgo(165) },
    { id: 'MTK-1027', customerId: 'usr-127', customerName: 'Vijay Mallya', email: 'vijay.m@gmail.com', mobile: '9866677889', items: [{ productId: 'prod-101', name: 'Rynox Air GT Jacket', price: 5999, quantity: 1 }], subtotal: 5999, grandTotal: 5999, paymentMethod: 'Razorpay', paymentStatus: 'Paid', orderStatus: 'Delivered', createdAt: daysAgo(175) },
  ];
  OrderModel.seedOrders(demoOrders);

  // 5. DEMO PAYMENTS (Connected to Orders)
  const demoPayments = demoOrders.map((ord, idx) => ({
    id: `pay-${1000 + idx}`,
    orderId: ord.id,
    customerName: ord.customerName,
    email: ord.email,
    mobile: ord.mobile,
    amount: ord.grandTotal,
    gateway: ord.paymentMethod.includes('COD') ? 'Cash on Delivery' : 'Razorpay',
    transactionId: ord.paymentMethod.includes('COD') ? `COD-${ord.id}` : `pay_RZP${882910 + idx}`,
    status: ord.paymentStatus,
    timestamp: ord.createdAt,
  }));
  PaymentModel.seedPayments(demoPayments);

  // 6. DEMO SHIPMENTS (Connected to Shipped/Delivered Orders)
  const shippedOrders = demoOrders.filter((o) => o.awb || o.orderStatus === 'Shipped' || o.orderStatus === 'Delivered');
  const demoShipments = shippedOrders.map((ord, idx) => ({
    id: `ship-${100 + idx}`,
    orderId: ord.id,
    customerName: ord.customerName,
    shippingAddress: `${ord.shippingAddress?.house}, ${ord.shippingAddress?.street}, ${ord.shippingAddress?.city}, ${ord.shippingAddress?.state} - ${ord.shippingAddress?.pincode}`,
    courier: ord.courier || 'BlueDart Express',
    awb: ord.awb || `BD${10293847 + idx}IN`,
    status: ord.orderStatus === 'Delivered' ? 'Delivered' : 'In Transit',
    dispatchDate: ord.createdAt,
    estimatedDelivery: ord.orderStatus === 'Delivered' ? ord.createdAt : daysAgo(-2),
  }));
  ShippingModel.seedShipments(demoShipments);

  // 7. DEMO SUPPLIERS
  const demoSuppliers = [
    {
      id: 'sup-101',
      name: 'Rynox Gears India Ltd',
      companyName: 'Rynox Gears Private Limited',
      contactPerson: 'Vikramaditya R.',
      phone: '+91 98200 11223',
      email: 'orders@rynoxgears.com',
      address: 'Mahape MIDC, Navi Mumbai, Maharashtra - 400710',
      gstin: '27AABCR9910E1Z4',
      status: 'Active',
      createdAt: daysAgo(60),
    },
    {
      id: 'sup-102',
      name: 'Viaterra Designs LLP',
      companyName: 'Viaterra Gear Designs',
      contactPerson: 'Manu Saxena',
      phone: '+91 98450 33445',
      email: 'sales@viaterragear.com',
      address: 'Coimbatore, Tamil Nadu - 641004',
      gstin: '33AAFCV8821B1Z2',
      status: 'Active',
      createdAt: daysAgo(50),
    },
    {
      id: 'sup-103',
      name: 'Motorradical India Pvt Ltd',
      companyName: 'Motorradical Adventure Accessories',
      contactPerson: 'Anand Rao',
      phone: '+91 99001 55667',
      email: 'info@motorradical.in',
      address: 'Bengaluru, Karnataka - 560027',
      gstin: '29AABCM7734C1Z9',
      status: 'Active',
      createdAt: daysAgo(45),
    },
    {
      id: 'sup-104',
      name: 'Scala Riding Apparel',
      companyName: 'Scala Gear India',
      contactPerson: 'Priya N.',
      phone: '+91 97110 99887',
      email: 'B2B@scalagear.com',
      address: 'New Delhi - 110015',
      gstin: '07AAACS1122D1Z1',
      status: 'Active',
      createdAt: daysAgo(40),
    },
    {
      id: 'sup-105',
      name: 'Axor & SMK Helmets Distribution',
      companyName: 'Vega Auto Accessories',
      contactPerson: 'Sameer K.',
      phone: '+91 98330 44556',
      email: 'distribution@axorhelmets.in',
      address: 'Pune, Maharashtra - 411019',
      gstin: '27AABCA5566F1Z8',
      status: 'Active',
      createdAt: daysAgo(35),
    },
  ];
  SupplierModel.seedSuppliers(demoSuppliers);

  // 8. DEMO POS BILLS (Offline Store Sales)
  const demoPosBills = [
    {
      id: 'MTK-BILL-1001',
      customerId: 'walk-in',
      customerName: 'Walk-in Customer',
      email: '',
      mobile: '',
      items: [{ name: 'Rynox Air GT Jacket', sku: 'RYN-BLK-L', quantity: 1, price: 5999, total: 5999 }],
      subtotal: 5999,
      discount: 0,
      tax: 1080,
      grandTotal: 5999,
      paymentMethod: 'Cash',
      paymentStatus: 'Paid',
      staffName: 'Pratik M.',
      createdAt: daysAgo(0, 14, 30),
    },
    {
      id: 'MTK-BILL-1002',
      customerId: 'usr-101',
      customerName: 'Rahul Sharma',
      email: 'rahul.s@gmail.com',
      mobile: '9823011234',
      items: [{ name: 'Viaterra Fly Magnetic Tank Bag', sku: 'VIA-BAG-001', quantity: 1, price: 2699, total: 2699 }],
      subtotal: 2699,
      discount: 0,
      tax: 486,
      grandTotal: 2699,
      paymentMethod: 'UPI',
      paymentStatus: 'Paid',
      staffName: 'Pratik M.',
      createdAt: daysAgo(0, 16, 15),
    },
    {
      id: 'MTK-BILL-1003',
      customerId: 'usr-102',
      customerName: 'Vikram Patel',
      email: 'vikram.patel@yahoo.com',
      mobile: '9890123456',
      items: [{ name: 'Mototrek Pro Touring Knee Guards', sku: 'MTK-KNEE-L', quantity: 1, price: 3499, total: 3499 }],
      subtotal: 3499,
      discount: 0,
      tax: 630,
      grandTotal: 3499,
      paymentMethod: 'Card',
      paymentStatus: 'Paid',
      staffName: 'Pratik M.',
      createdAt: daysAgo(1, 11, 20),
    },
    {
      id: 'MTK-BILL-1004',
      customerId: 'walk-in',
      customerName: 'Walk-in Customer',
      email: '',
      mobile: '',
      items: [{ name: 'Motorradical Aluminium Top Case 45L', sku: 'MRD-TC-45L', quantity: 1, price: 24999, total: 24999 }],
      subtotal: 24999,
      discount: 1000,
      tax: 4320,
      grandTotal: 23999,
      paymentMethod: 'UPI',
      paymentStatus: 'Paid',
      staffName: 'Pratik M.',
      createdAt: daysAgo(2, 17, 45),
    },
    {
      id: 'MTK-BILL-1005',
      customerId: 'usr-103',
      customerName: 'Amit Kumar',
      email: 'amit.k@outlook.com',
      mobile: '9765432109',
      items: [{ name: 'Scala Trekker Riding Boots', sku: 'SCL-BOT-42', quantity: 1, price: 6499, total: 6499 }],
      subtotal: 6499,
      discount: 0,
      tax: 1170,
      grandTotal: 6499,
      paymentMethod: 'Card',
      paymentStatus: 'Paid',
      staffName: 'Pratik M.',
      createdAt: daysAgo(4, 13, 10),
    },
    {
      id: 'MTK-BILL-1006',
      customerId: 'walk-in',
      customerName: 'Walk-in Customer',
      email: '',
      mobile: '',
      items: [{ name: 'Rynox Advento Riding Pants', sku: 'RYN-PNT-M', quantity: 1, price: 4999, total: 4999 }],
      subtotal: 4999,
      discount: 0,
      tax: 900,
      grandTotal: 4999,
      paymentMethod: 'Cash',
      paymentStatus: 'Paid',
      staffName: 'Pratik M.',
      createdAt: daysAgo(6, 18, 0),
    },
  ];
  PosBillModel.seedPosBills(demoPosBills);

  // 9. DEMO PURCHASE ORDERS (Supplier Purchase Orders)
  const demoPOs = [
    {
      id: 'PI-1001',
      supplierId: 'sup-101',
      supplierName: 'Rynox Gears India Ltd',
      purchaseDate: daysAgo(20).slice(0, 10),
      items: [{ name: 'Rynox Air GT Jacket', sku: 'RYN-BLK-L', quantity: 20, unitCost: 3800, totalCost: 76000 }],
      subtotalCost: 76000,
      taxCost: 13680,
      totalPurchaseCost: 89680,
      paymentStatus: 'Paid',
      status: 'Received',
      receivedAt: daysAgo(18),
      notes: 'Summer stock batch received in good condition.',
    },
    {
      id: 'PI-1002',
      supplierId: 'sup-102',
      supplierName: 'Viaterra Designs LLP',
      purchaseDate: daysAgo(15).slice(0, 10),
      items: [{ name: 'Viaterra Fly Magnetic Tank Bag', sku: 'VIA-BAG-001', quantity: 15, unitCost: 1700, totalCost: 25500 }],
      subtotalCost: 25500,
      taxCost: 4590,
      totalPurchaseCost: 30090,
      paymentStatus: 'Paid',
      status: 'Received',
      receivedAt: daysAgo(13),
      notes: 'Tank bags restocked.',
    },
    {
      id: 'PI-1003',
      supplierId: 'sup-103',
      supplierName: 'Motorradical India Pvt Ltd',
      purchaseDate: daysAgo(10).slice(0, 10),
      items: [{ name: 'Motorradical Aluminium Top Case 45L', sku: 'MRD-TC-45L', quantity: 5, unitCost: 16500, totalCost: 82500 }],
      subtotalCost: 82500,
      taxCost: 14850,
      totalPurchaseCost: 97350,
      paymentStatus: 'Paid',
      status: 'Received',
      receivedAt: daysAgo(8),
      notes: 'Premium aluminium luggage cases.',
    },
    {
      id: 'PI-1004',
      supplierId: 'sup-104',
      supplierName: 'Scala Riding Apparel',
      purchaseDate: daysAgo(3).slice(0, 10),
      items: [{ name: 'Scala Trekker Riding Boots', sku: 'SCL-BOT-42', quantity: 10, unitCost: 4100, totalCost: 41000 }],
      subtotalCost: 41000,
      taxCost: 7380,
      totalPurchaseCost: 48380,
      paymentStatus: 'Pending',
      status: 'Ordered',
      notes: 'Boots batch expected next week.',
    },
  ];
  PurchaseOrderModel.seedPurchaseOrders(demoPOs);

  // 10. DEMO ACCOUNTS TRANSACTIONS (Financial Ledger)
  const demoTransactions = [];

  // Feed Online Sales
  demoOrders.forEach((ord) => {
    demoTransactions.push({
      id: `TRANS-ORD-${ord.id}`,
      date: ord.createdAt,
      reference: ord.id,
      type: 'Online Sale',
      description: `Website Order from ${ord.customerName}`,
      income: ord.grandTotal,
      expense: 0,
      paymentMethod: ord.paymentMethod,
      source: 'Online Website Storefront',
    });
  });

  // Feed Offline POS Sales
  demoPosBills.forEach((bill) => {
    demoTransactions.push({
      id: `TRANS-BILL-${bill.id}`,
      date: bill.createdAt,
      reference: bill.id,
      type: 'Offline Sale',
      description: `Store POS Bill for ${bill.customerName}`,
      income: bill.grandTotal,
      expense: 0,
      paymentMethod: bill.paymentMethod,
      source: 'Physical Store POS',
    });
  });

  // Feed Supplier Purchases
  demoPOs.forEach((po) => {
    demoTransactions.push({
      id: `TRANS-PO-${po.id}`,
      date: po.purchaseDate,
      reference: po.id,
      type: 'Stock Purchase',
      description: `Supplier Stock Purchase PO from ${po.supplierName}`,
      income: 0,
      expense: po.totalPurchaseCost,
      paymentMethod: 'Bank Transfer',
      source: 'Suppliers & Purchases',
    });
  });

  // Operating Expenses
  demoTransactions.push(
    {
      id: 'TRANS-EXP-101',
      date: daysAgo(28),
      reference: 'EXP-RENT-AUG',
      type: 'Operating Expense',
      description: 'Physical Store & Showroom Rent - August 2026',
      income: 0,
      expense: 45000,
      paymentMethod: 'Bank Transfer',
      source: 'Accounts',
    },
    {
      id: 'TRANS-EXP-102',
      date: daysAgo(22),
      reference: 'EXP-ELEC-AUG',
      type: 'Operating Expense',
      description: 'Electricity & Air Conditioning Bill',
      income: 0,
      expense: 8200,
      paymentMethod: 'UPI',
      source: 'Accounts',
    },
    {
      id: 'TRANS-EXP-103',
      date: daysAgo(15),
      reference: 'EXP-SALARY-AUG',
      type: 'Operating Expense',
      description: 'Staff & Technicians Monthly Salary',
      income: 0,
      expense: 65000,
      paymentMethod: 'Bank Transfer',
      source: 'Accounts',
    },
    {
      id: 'TRANS-EXP-104',
      date: daysAgo(7),
      reference: 'EXP-MKTG-101',
      type: 'Operating Expense',
      description: 'Instagram & YouTube Rider Ads Campaign',
      income: 0,
      expense: 12000,
      paymentMethod: 'Card',
      source: 'Accounts',
    }
  );

  AccountsModel.seedTransactions(demoTransactions);

  console.log(`✅ Demo Data Seeded Successfully!`);
  console.log(`- Customers: ${demoUsers.length}`);
  console.log(`- Products: ${demoProducts.length}`);
  console.log(`- Orders: ${demoOrders.length}`);
  console.log(`- Coupons: ${demoCoupons.length}`);
  console.log(`- Payments: ${demoPayments.length}`);
  console.log(`- Shipments: ${demoShipments.length}`);
  console.log(`- POS Bills: ${demoPosBills.length}`);
  console.log(`- Suppliers: ${demoSuppliers.length}`);
  console.log(`- Purchase Orders: ${demoPOs.length}`);
  console.log(`- Financial Transactions: ${demoTransactions.length}`);
};

// Execute if run directly via node CLI
if (require.main === module) {
  seedDemoData();
}

module.exports = {
  seedDemoData,
};

